### ISSUE TITLE
Cannot install v0.9.3+ because of UnicodeDecodeError

### ISSUE THREAD

**Issue by sibbl** [aio-libs/yarl#60] opened 2017-02-16 20:46 UTC
Today I wanted to upgrade home assistant to the newest version in my virtualenv on my RPi3. Unfortunately this was not possible as the build of `yarl` failed. Turns out that the root of this problem is somewhere between v0.9.2 and 0.9.3, see the following error

```
Installing collected packages: yarl
  Found existing installation: yarl 0.9.2
    Uninstalling yarl-0.9.2:
      Successfully uninstalled yarl-0.9.2
  Running setup.py install for yarl ... error
  Rolling back uninstall of yarl
Exception:
Traceback (most recent call last):
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/pip/compat/__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 28: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/pip/utils/__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/pip/compat/__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 28: invalid start byte
```

**Comment by juulie** [comment] 2017-02-23 19:29
Same problem here for 0.9.8
Exception:
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/pip/compat/__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe6 in position 3: invalid continuation byte

**Comment by sibbl** [comment] 2017-02-23 21:11
In the meantime a new version of aiohttp was released, which should fix the issue for home assistant. Did you try installing the newest version?

**Comment by juulie** [comment] 2017-02-23 22:41
latest aiohttp requires yarl 0.9.8 right?

**Comment by fafhrd91** [comment] 2017-03-14 19:27
is this still a problem?

**Comment by AraHaan** [comment] 2017-03-19 02:37
not for me, the only problem I get is in issue #67

**Comment by fxxer** [comment] 2017-04-09 12:59
I have the same problem

`Installing collected packages: yarl
  Running setup.py install for yarl ... error
Exception:
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/pip/compat/__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbd in position 4: invalid start byte`

**Comment by asvetlov** [comment] 2017-04-11 14:56
I cannot reproduce the issue.
Could you provide more detailed info:
* Steps to reproduce
* OS
* `LANG` and `LC_*` environment variables

Maybe the library compilation generates errors with non-english text with non utf8 locale?

**Comment by fxxer** [comment] 2017-04-11 20:37
Sure,

Installing on the latest raspbian lite distro and locale is default en_GB.UTF-8 UTF-8
Do you need any other info?

```
pip install --no-cache-dir yarl
Collecting yarl
  Downloading yarl-0.10.0.tar.gz (127kB)
    100% |################################| 133kB 1.9MB/s 
Requirement already satisfied: multidict>=2.0 in /srv/homeassistant/lib/python3.4/site-packages (from yarl)
Installing collected packages: yarl
  Running setup.py install for yarl ... error
Exception:
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/pip/compat/__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9e in position 1: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/srv/homeassistant/lib/python3.4/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/srv/homeassistant/lib/python3.4/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/srv/homeassistant/lib/python3.4/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/srv/homeassistant/lib/python3.4/site-packages/pip/utils/__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "/srv/homeassistant/lib/python3.4/site-packages/pip/compat/__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9e in position 1: invalid start byte
```

**Comment by netstuff** [comment] 2017-04-17 15:08
Hi, have a same issue on Windows 10.

```
pip install aiohttp --no-cache-dir
Collecting aiohttp
  Downloading aiohttp-2.0.7.tar.gz (739kB)
    100% |████████████████████████████████| 747kB 12.8MB/s
Requirement already satisfied: chardet in d:\devel\kotlin\venv\lib\site-packages (from aiohttp)
Requirement already satisfied: multidict>=2.1.4 in d:\devel\kotlin\venv\lib\site-packages (from aiohttp)
Collecting async_timeout>=1.2.0 (from aiohttp)
  Downloading async_timeout-1.2.0-py3-none-any.whl
Collecting yarl<0.11,>=0.10.0 (from aiohttp)
  Downloading yarl-0.10.0.tar.gz (127kB)
    100% |████████████████████████████████| 133kB 8.2MB/s
Installing collected packages: async-timeout, yarl, aiohttp
  Running setup.py install for yarl ... error
Exception:
Traceback (most recent call last):
  File "d:\devel\kotlin\venv\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 3: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\devel\kotlin\venv\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "d:\devel\kotlin\venv\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "d:\devel\kotlin\venv\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "d:\devel\kotlin\venv\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "d:\devel\kotlin\venv\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "d:\devel\kotlin\venv\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 3: invalid continuation byte
```

**Comment by fafhrd91** [comment] 2017-04-17 16:31
might related to Cyrillic chars in readme.

**Comment by AraHaan** [comment] 2017-05-03 16:33
I think it has something to do with pip. I does not happen to me yet though. Although I am using Windows so.

**Comment by fxxer** [comment] 2017-05-03 16:38
I did a clean install and migrate my setting .. yarl upgrade went without a problem. I asume it has to be an issue with localization.

**Comment by asvetlov** [comment] 2017-05-20 04:51
Let's close the issue. Feel free to create new one if the problem is still here.

**Closed by asvetlov** 2017-05-20 04:51 UTC
